#!/usr/bin/env python3
"""Add second EMEA ECM screenshot batch to Global AI Pre-IPO tracker.

Source boundary: user phone screenshots OCR + public-source enrichment as of 2026-07-01.
This is intentionally conservative: screenshot banker-list valuations that could not be matched to public sources are preserved as low/medium confidence notes rather than treated as verified priced rounds.
"""
from __future__ import annotations
import json, re
from pathlib import Path

APP = Path(__file__).resolve().parents[1]
STATE = APP / 'data' / 'state.json'
NOW = '2026-07-01T12:35:00Z'
ASOF = '2026-07-01'

def slug(s):
    return re.sub(r'[^a-z0-9]+','-',str(s).lower()).strip('-') or 'item'

def ev(date, typ, note, url, confidence='medium'):
    return {'date': date, 'type': typ, 'note': note, 'url': url, 'confidence': confidence}

def fr(cid, name, date, round_, amount, valuation, lead, parts, source, stype, url, conf='medium', notes=''):
    return {'id': f'{cid}-{slug(date)}-{slug(round_)}', 'companyId': cid, 'companyName': name, 'date': date, 'round': round_, 'amount': amount, 'valuation': valuation, 'leadInvestors': lead, 'participants': parts, 'sourceName': source, 'sourceType': stype, 'url': url, 'confidence': conf, 'notes': notes}

def task(cid, title, pri='Medium'):
    return {'id': f'task-emea-ecm-b2-{cid}-{slug(title)[:40]}', 'companyId': cid, 'title': title, 'owner': 'Deal Team', 'dueDate': '2026-07-18', 'status': 'open', 'priority': pri, 'category': 'diligence', 'notes': 'Added from second EMEA ECM screenshot batch 2026-07-01; current live secondary/primary availability still requires banker/data-room confirmation.'}

def comp(id, name, country, sector, sub, valuation, funding, investors, evs, metrics, summary, risks, diligence, *, priority='B2｜EMEA ECM watch / needs data-room proof', layer='EMEA ECM / TMT private opportunity', region='EMEA', risk='medium_high', ipo='medium', revenueq='medium', tags=None, ipo_window='24–48m watch', stage='late_growth_pre_ipo'):
    tags = tags or []
    return {
        'id': id, 'name': name, 'country': country, 'region': region, 'sector': sector, 'subSector': sub,
        'stage': stage, 'status': 'private', 'ipoSignal': ipo, 'revenueQuality': revenueq, 'investorQuality': 'high' if investors else 'medium', 'strategicRelevance': 'medium_high', 'accessFit': 'medium', 'riskLevel': risk,
        'latestValuation': valuation, 'latestFunding': funding, 'investors': investors,
        'ipoSignals': ['Included in EMEA ECM pre-IPO/private opportunities screenshot', 'No filing verified unless explicitly stated in evidence'],
        'nextAction': diligence,
        'tags': sorted(set(tags + ['EMEA ECM screenshot 2026-07-01', 'private/pre-IPO'])),
        'evidence': evs,
        'notes': 'Second EMEA ECM screenshot batch; public-source enriched as of 2026-07-01. Treat screenshot valuations as banker-list seeds unless matched to official/media priced rounds.',
        'dealStage': 'relationship sourcing', 'dataRoomStatus': 'not requested', 'targetExchange': 'TBD', 'leadUnderwriters': [], 'krxReviewStatus': None, 'lockup': 'TBD', 'preIpoRoundStatus': 'public-source only; live transaction terms unverified', 'contacts': [], 'redFlags': [], 'openQuestions': [],
        'priorityTier': priority, 'layer': layer, 'whyInTrack': summary, 'revenueScale': metrics,
        'relationshipRoute': 'EMEA ECM/private capital + existing growth/crossover/shareholder route → current secondary, primary extension, IPO anchor/cornerstone or data-room access.',
        'investorGroup': 'EMEA ECM / crossover growth', 'keyDiligence': diligence,
        'disruptedLegacyTech': 'EMEA private/pre-IPO capital-markets opportunity sourced from ECM list; AI-core relevance varies by company.',
        'ipoWindow': ipo_window, 'updatedAt': NOW, 'companyDescription': f'{sector} — {sub}', 'latestAvailableValuation': valuation,
        'investorSummary': ', '.join(investors[:8]), 'investorDataQuality': 'medium_high' if investors else 'medium', 'dataCompleteness': 'medium', 'enrichedAsOf': ASOF,
        'layerZh': layer, 'homepageDescriptionZh': f'{sector} — {sub}', 'latestValuationZh': valuation, 'revenueScaleZh': metrics, 'nextActionZh': diligence, 'priorityZh': priority,
        'notesClean': 'EMEA ECM screenshot enrichment; requires banker/data-room confirmation.', 'recommendationClean': '加入EMEA ECM观察池；以公开数据建立首版卡片，下一步核验当前可交易条款、收入质量和IPO路径。', 'presentationLanguage': 'zh-CN', 'presentationCleanedAsOf': ASOF,
        'investmentSummaryZh': summary, 'riskSummaryZh': risks, 'keyMetrics': [m.strip() for m in metrics.split(';') if m.strip()][:8], 'readinessLabel': 'B：Route-ready / diligence-ready'
    }

companies = [
comp('legora','Legora','Sweden','TMT / AI workplace tools','AI legal/workplace collaboration tools; formerly Leya, AI workspace for legal/professional work','Screenshot seed: $5.6B last valuation — not corroborated in public sources in this pass; public media has lower earlier funding/valuation marks','Public media: 2025 Series B / growth funding; exact latest public valuation below screenshot and needs verification',['ICONIQ Capital','General Catalyst','Benchmark','Redpoint','Y Combinator'],[ev('2025','media','Public reports describe Legora/Leya as a Swedish AI legal-workplace platform with major VC funding; screenshot $5.6B not treated as verified priced round.','https://www.legora.com/','medium'),ev('2025','company','Legora official site/product source for AI workspace positioning.','https://www.legora.com/','medium_high')],'ARR/revenue not publicly verified; customer logos/usage require data-room proof','Legora — 高增长AI workplace/legal-tech seed，但截图$5.6B未被公开来源核验，先放B2 watch；若banker能给真实round/secondary terms再上调。','主要风险：估值未公开佐证、法律/企业工作流被大模型平台压缩、ARR和留存未公开。','Verify current round/secondary docs, ARR, enterprise/legal customer retention, gross margin, data/privacy controls and valuation support.',tags=['Sweden','AI workplace','legal AI']),
comp('lendable','Lendable','United Kingdom','TMT / Consumer lending platform','AI/data-driven consumer credit platform and institutional loan marketplace','Screenshot seed: $4.7B; public 2022 reports valued Lendable at more than £3.5B (~$4.6B), broadly consistent but stale','2022 primary+secondary financing around £210M / $210M equivalent led by Ontario Teachers; current funding not verified',['Ontario Teachers’ Pension Plan','Goldman Sachs','Oaktree','Waterfall Asset Management'],[ev('2022-03-10','media','Reuters: UK fintech Lendable valued at more than £3.5B in funding round.','https://www.reuters.com/markets/deals/uk-fintech-lendable-valued-more-than-35-billion-funding-round-2022-03-10/','medium_high'),ev('2026','official','Company site positions Lendable as technology-enabled consumer finance platform.','https://www.lendable.co.uk/','medium')],'Public detailed revenue/profit not verified; lending volumes, loss rates and funding cost require data room','Lendable — UK consumer-lending平台，截图估值与2022公开估值大致一致但已旧；核心看credit cycle、funding facility和净息/坏账质量。','主要风险：消费信贷周期、资金成本、坏账/ECL、监管与消费者保护、估值陈旧。','Request loan book, vintage loss curves, funding facilities, net interest margin, take rate, current secondary mark and IPO plan.',tags=['UK','consumer finance','credit'],risk='high',ipo='medium_low'),
comp('mews','Mews','Netherlands','TMT / Hospitality software','Cloud PMS and hotel management software platform','Screenshot seed: $2.5B; public sources show lower earlier unicorn/late-stage valuations, current $2.5B needs verification','Public 2024/2025 growth rounds and credit facilities; exact latest priced valuation requires verification',['Kinnevik','Goldman Sachs Alternatives','Revaia','Notion Capital','LGVP','Battery Ventures'],[ev('2024','official','Mews official newsroom/product site for cloud hospitality platform and funding context.','https://www.mews.com/en/news','medium_high'),ev('2024','media','TechCrunch covered Mews unicorn/growth funding; use as valuation history not current banker mark.','https://techcrunch.com/','medium')],'Public metrics include thousands of hotel customers/locations in company materials; ARR/revenue/profit not fully public here','Mews — 酒店软件垂直SaaS，行业恢复+cloud PMS替代逻辑清楚；截图$2.5B需要用最新round/secondary核验。','主要风险：酒店周期、implementation复杂、Oracle Hospitality/Cloudbeds竞争、估值与ARR支撑。','Verify ARR, NRR, gross margin, customer count, enterprise vs SMB mix, current valuation and IPO/tender timeline.',tags=['Netherlands','hospitality SaaS']),
comp('mirakl','Mirakl','France','TMT / Marketplace SaaS','SaaS platform for e-commerce marketplaces, dropship and retail media','Publicly verified: >$3.5B valuation in Sep 2021 $555M Series E; screenshot $3.5B consistent but stale','Sep 2021 $555M Series E led by Silver Lake; no newer public priced round verified',['Silver Lake','Permira','83North','Felix Capital','Elaia','Bpifrance'],[ev('2021-09-21','official','Mirakl official: $555M Series E led by Silver Lake, valuing company at over $3.5B.','https://www.mirakl.com/news/mirakl-raises-555m-series-e-funding','high'),ev('2021-09-21','media','TechCrunch: Mirakl raises $555M at $3.5B+ valuation.','https://techcrunch.com/2021/09/21/mirakl-raises-555-million-for-its-marketplace-platform/','medium_high')],'Company/customer metrics public in marketing; ARR/revenue not verified in this pass','Mirakl — EMEA marketplace SaaS老牌独角兽，估值来源清楚但2021较旧；需补当前ARR/盈利和IPO意愿。','主要风险：2021高估值陈旧、enterprise commerce预算周期、marketplace模块被Shopify/Salesforce/Adobe等平台挤压。','Request current ARR/NRR, GM, Rule-of-40, retail media/dropship growth, current secondary price and IPO banker status.',tags=['France','marketplace SaaS'],ipo='medium'),
comp('multiverse-computing','Multiverse Computing','Spain','TMT / AI model compression','Quantum-inspired AI model compression and optimization; CompactifAI','Screenshot seed $500M; public 2025 Series B reports imply around $500M valuation','2025 Series B around €189M / $215M led by Bullhound and strategic investors',['Bullhound Capital','HP Tech Ventures','Forgepoint Capital','CDP Venture Capital','Santander','Toshiba'],[ev('2025','official','Company site positions CompactifAI / quantum-inspired AI model compression products.','https://multiversecomputing.com/','medium_high'),ev('2025','media','Media reports: Multiverse Computing raised large Series B around €189M/$215M at roughly $500M valuation.','https://techcrunch.com/','medium')],'Commercial revenue not fully public; needs paid deployment proof for model-compression economics','Multiverse Computing — AI模型压缩/quantum-inspired优化，主题相关但商业化更早期；截图$500M大致可接受但需核验round docs。','主要风险：技术benchmarks转收入、模型压缩被开源/大厂吸收、客户部署周期、quantum标签噪音。','Verify Series B documents, revenue/backlog, compression benchmarks on production LLMs, customer references, gross margin and IPO horizon.',priority='C1｜Tech radar / early commercial proof needed',tags=['Spain','AI compression','quantum-inspired'],ipo='low',revenueq='low'),
comp('n8n','n8n','Germany','TMT / AI agents for businesses','Workflow automation and AI agent orchestration platform for developers/businesses','Screenshot seed $5.2B not corroborated by public sources in this pass; public funding valuations appear lower/stale','Public 2025/2026 funding reports exist but latest $5.2B needs banker/data-room verification',['Highland Europe','Sequoia Capital','Felix Capital','HV Capital'],[ev('2026','official','n8n official site/product source for workflow automation and AI agent platform positioning.','https://n8n.io/','medium_high'),ev('2025','media','Public media covered n8n funding and AI-workflow growth; screenshot $5.2B needs direct verification.','https://techcrunch.com/','medium')],'Usage/community metrics public; ARR/revenue not verified here','n8n — workflow automation/AI agent平台，方向很强但截图$5.2B未公开佐证；先列为B2/C2之间，重点核ARR和付费企业留存。','主要风险：开源商业化、Zapier/Make/Microsoft/ServiceNow竞争、AI agent平台同质化、估值未核验。','Verify current valuation, ARR, paid enterprise mix, open-source-to-paid conversion, retention, gross margin and security/compliance readiness.',tags=['Germany','AI agents','workflow automation']),
comp('nord-security','Nord Security','Lithuania','TMT / Digital security','Consumer and business cybersecurity/privacy products including VPN, password manager and threat protection','Publicly verified: $3B valuation in Sep 2023 round; screenshot $3B consistent','Sep 2023 $100M financing led by Warburg Pincus; Apr 2022 $100M at $1.6B led by Novator',['Warburg Pincus','Novator Ventures','General Catalyst','Burda Principal Investments'],[ev('2023-09-28','official','Nord Security official: $100M financing led by Warburg Pincus at $3B valuation.','https://nordsecurity.com/blog/nord-security-raises-100m','high'),ev('2022-04','official','Nord Security official/press materials: $100M raise at $1.6B valuation led by Novator.','https://nordsecurity.com/','medium_high')],'Public customer/subscriber metrics need verification; revenue/profit not publicly audited here','Nord Security — 数字隐私/cyber消费+企业安全资产，截图$3B可公开佐证；需判断consumer VPN增长质量和IPO路径。','主要风险：VPN市场竞争/价格、平台政策、隐私信任、B2B转型质量、订阅留存。','Verify revenue, EBITDA, subscriber cohorts, B2B NordLayer growth, CAC/payback, app-store/platform risk and IPO banker status.',tags=['Lithuania','cybersecurity','VPN'],ipo='medium_high',revenueq='medium'),
comp('odoo','Odoo','Belgium','TMT / Business management software','Open-source integrated ERP/business management software for SMEs','Screenshot seed $8.2B; public secondary/valuation reports around €5B+ to €7B+ need verification vs FX/timing','Recent secondary/growth transactions reported; exact current valuation requires confirmation',['Summit Partners','General Atlantic','Noshaq','Sofinnova Partners','SRIW'],[ev('2021','official','Odoo newsroom/source for historical funding and investor base; open-source ERP/business apps positioning.','https://www.odoo.com/blog/odoo-news-5','medium'),ev('2024','media','European media reported large secondary/valuation step-up for Odoo; screenshot $8.2B requires confirmation.','https://www.odoo.com/','medium')],'Company has large user/community footprint; ARR/revenue/profit not fully captured here','Odoo — 比利时ERP/SMB business software成熟资产，开源+SMB ERP替代逻辑清楚；截图$8.2B需用最新secondary核验。','主要风险：SMB周期、implementation/partner质量、开源商业化、估值与ARR/利润匹配。','Verify latest secondary valuation, ARR/revenue, EBITDA, partner channel economics, churn/NRR and IPO readiness.',priority='B1｜EMEA mature software / secondary valuation check',tags=['Belgium','ERP','business software'],ipo='medium_high'),
comp('oxford-quantum-circuits','Oxford Quantum Circuits','United Kingdom','TMT / Quantum computing','Superconducting quantum computers and quantum-computing-as-a-service','Valuation undisclosed in screenshot and public Series B; keep valuation undisclosed','Nov 2023 $100M Series B led by SBI Investment; valuation undisclosed',['SBI Investment','Oxford Science Enterprises','University of Tokyo Edge Capital','Lansdowne Partners','Prosus Ventures'],[ev('2023-11-27','official','OQC official: $100M Series B, led by SBI Investment, to expand quantum computers and QCaaS.','https://oqc.tech/news/oqc-raises-100m-series-b/','high'),ev('2026','official','OQC official site/product source for superconducting quantum computers.','https://oqc.tech/','high')],'Commercial revenue not public; quantum hardware roadmap and customer pilots need verification','OQC — UK quantum硬科技观察，不应按传统TMT pre-IPO估值交易；以技术milestone、政府/云客户和融资 runway 为主。','主要风险：量子商业化时间长、硬件roadmap、资本强度、客户收入有限、与IonQ/Rigetti/Quantinuum等竞争。','Verify qubit roadmap, error rates, cloud/customer revenue, grant/non-dilutive funding, cash runway and strategic/IPO route.',priority='C1｜Quantum tech radar / long-duration',tags=['UK','quantum computing'],ipo='low',revenueq='low'),
comp('personio','Personio','Germany','TMT / HR software','HR management, payroll and recruiting software for SMEs','Publicly verified: $8.5B valuation in Jun 2022 Series E extension; screenshot $8.5B consistent but stale','$200M Series E extension Jun 2022; prior $270M Series E Oct 2021',['Greenoaks','Altimeter','Index Ventures','Accel','Meritech','Lightspeed','Northzone','Global Founders Capital'],[ev('2022-06-22','official','Personio official: $200M Series E extension at $8.5B valuation.','https://www.personio.com/about-personio/press/personio-raises-200-million-series-e-extension/','high'),ev('2021-10','official','Personio official: $270M Series E at $6.3B valuation; historical context.','https://www.personio.com/about-personio/press/','medium_high')],'Company disclosed 10k+ customers/SMB footprint in public materials; current ARR/profit not verified here','Personio — EMEA HR SaaS成熟独角兽，截图估值有公开来源但为2022 vintage；需用ARR/NRR和当前secondary折价重估。','主要风险：SMB软件预算、HR/payroll本地化、竞争、2022估值重估、profitability。','Verify current ARR, NRR, payroll attach, gross margin, CAC payback, secondary pricing and IPO banker status.',priority='B1｜EMEA mature SaaS / stale valuation reset',tags=['Germany','HR SaaS'],ipo='medium'),
comp('poolside','Poolside','France','TMT / AI coding software','Foundation-model and AI coding software company focused on code generation','Publicly verified by media: $3B valuation in Oct 2024 $500M Series B; screenshot $3B consistent','$500M Series B Oct 2024 led by Bain Capital Ventures with strategic/financial investors',['Bain Capital Ventures','DST Global','NVIDIA','eBay','Felicis','Redpoint'],[ev('2024-10','media','TechCrunch: Poolside raised $500M at $3B valuation to build AI for code.','https://techcrunch.com/2024/10/02/poolside-raises-500m-from-e-bay-nvidia-and-others-to-build-a-code-gen-ai/','medium_high'),ev('2026','official','Poolside official site/product source for AI coding/foundation-model positioning.','https://poolside.ai/','medium_high')],'Revenue/ARR not publicly verified; likely pre-revenue/early commercial relative to valuation','Poolside — 法国AI coding模型公司，估值/融资清楚但商业化证据薄；与Lovable/Cursor/GitHub Copilot等竞争，需谨慎。','主要风险：高估值早期商业化、基础模型训练成本、开发者工具竞争、分发弱于平台。','Verify product revenue, enterprise pilots, model performance vs Copilot/Cursor/Lovable, compute commitments and gross margin path.',priority='B2｜AI coding model / high valuation early commercialization',tags=['France','AI coding','foundation model'],risk='high',ipo='medium_low',revenueq='low'),
comp('qonto','Qonto','France','TMT / SME finance tools','Business banking and finance-management tools for SMEs and freelancers','Publicly verified: €4.4B / ~$5B valuation in Jan 2022 Series D; screenshot $5B consistent but stale','€486M Series D Jan 2022 led by Tiger Global and TCV',['Tiger Global','TCV','Tencent','DST Global','Alkeon','Valar','Eurazeo','Korelya'],[ev('2022-01-11','official','Qonto official: €486M Series D and €4.4B valuation.','https://qonto.com/en/press/qonto-series-d','high'),ev('2022-01-11','media','TechCrunch: Qonto raises $552M Series D at $5B valuation.','https://techcrunch.com/2022/01/11/qonto-raises-552-million-series-d-for-its-business-banking-service/','medium_high')],'Public customer count has grown materially; current revenue/profit not verified here','Qonto — 法国SME fintech/SaaS-bank混合资产，2022估值清楚但需重估；核心看客户增长、收入/客户、合规和盈利路径。','主要风险：利率/银行监管、SME周期、竞争、2022估值陈旧、跨国扩张复杂。','Verify customers, revenue/ARR, take rate, credit exposure, regulatory capital, profitability and current secondary/IPO plans.',priority='B1｜EMEA SME fintech / stale valuation reset',tags=['France','SME finance','fintech'],ipo='medium'),
comp('quantexa','Quantexa','United Kingdom','TMT / Business intelligence & data platform','Decision intelligence, entity resolution and financial-crime/data platform','Publicly verified: $2.6B valuation in Mar 2025 Series F; screenshot $2.6B consistent','$175M Series F Mar 2025 led by Teachers’ Venture Growth / Ontario Teachers',['Ontario Teachers / TVG','Warburg Pincus','Dawn Capital','AlbionVC','HSBC','BNY','ABN AMRO'],[ev('2025-03','official','Quantexa official: $175M Series F at $2.6B valuation to accelerate decision intelligence platform.','https://www.quantexa.com/resources/quantexa-announces-175m-series-f-funding-round/','high'),ev('2023-04','official','Quantexa official: $129M Series E at $1.8B valuation; historical step-up.','https://www.quantexa.com/resources/quantexa-announces-129m-series-e-funding-round/','high')],'ARR/revenue not fully public; enterprise financial-crime/customer logos public','Quantexa — UK decision intelligence/data platform，2025估值新且公开；本批TMT中较干净，需补ARR/NRR和financial-crime/platform扩张质量。','主要风险：企业销售周期、Palantir/SAS/FICO/Quantexa替代竞争、金融客户集中、AI/data平台叙事过热。','Verify ARR, NRR, gross margin, financial-crime vs broader data-platform mix, top-customer concentration and IPO timetable.',priority='A2｜EMEA enterprise data platform / fresh valuation',tags=['UK','decision intelligence','data platform'],ipo='medium_high',revenueq='medium_high'),
comp('thought-machine','Thought Machine','United Kingdom','TMT / Core banking software','Cloud-native core banking and digital transformation software for banks','Public prior valuation: around $2.7B in 2022 Series D; screenshot $2.1B may reflect later mark and needs verification','$160M Series D May 2022; later strategic extensions/investments reported',['Temasek','Intesa Sanpaolo','Morgan Stanley','JPMorgan Chase','Lloyds Banking Group','Eurazeo'],[ev('2022-05','official','Thought Machine official: $160M Series D round; cloud-native core banking platform.','https://www.thoughtmachine.net/news/thought-machine-raises-160m-series-d','high'),ev('2022','media','Media reported Series D valuation around $2.7B; screenshot $2.1B needs current secondary verification.','https://techcrunch.com/','medium')],'Revenue not public; bank customer wins/logos require validation by deployment status not announcements','Thought Machine — 核心银行系统替代逻辑强但sales/implementation周期长；截图$2.1B可能是估值回调，需核当前mark。','主要风险：银行核心迁移周期、implementation失败风险、客户合同与收入确认、Temenos/Mambu/FIS/Finacle竞争。','Verify live production banks, ARR/backlog, implementation margins, churn, current valuation and IPO strategy.',tags=['UK','core banking','bank software'],risk='medium_high'),
comp('trendyol','Trendyol','Turkey','TMT / E-commerce marketplace','Turkish e-commerce and marketplace platform with logistics/payments ecosystem','Publicly verified: $16.5B valuation in Aug 2021 $1.5B round; screenshot $16.5B consistent but stale','$1.5B Aug 2021 round led by General Atlantic, SoftBank, ADQ/QIA and others; Alibaba is major shareholder',['Alibaba','General Atlantic','SoftBank Vision Fund','ADQ','Qatar Investment Authority','Princeville Capital'],[ev('2021-08-09','media','TechCrunch: Trendyol raised $1.5B at $16.5B valuation.','https://techcrunch.com/2021/08/09/turkeys-trendyol-raises-1-5b-at-a-16-5b-valuation/','medium_high'),ev('2021-08','media','Reuters coverage of $1.5B fundraising/valuation; Alibaba-backed Turkish e-commerce leader.','https://www.reuters.com/technology/alibaba-backed-trendyol-raises-15-bln-165-bln-valuation-2021-08-09/','medium_high')],'Public GMV/revenue/profit not verified here; Turkey market leadership and international expansion need current data','Trendyol — 土耳其电商平台巨头，估值来源清楚但2021 vintage很旧；币值/宏观/竞争使当前估值必须重估。','主要风险：土耳其宏观/FX、e-commerce margin、Alibaba control/exit route、competition、regulatory/geopolitical risk。','Verify current GMV/revenue/EBITDA, FX-adjusted growth, ownership/Alibaba exit plan, IPO venue and current valuation.',tags=['Turkey','e-commerce','Alibaba'],risk='high',ipo='medium'),
comp('wayve','Wayve','United Kingdom','TMT / Autonomous driving AI','Embodied AI / end-to-end autonomous driving software','Screenshot seed $8.6B; public May 2024 Series C amount $1.05B, valuation widely reported but not official in company release','$1.05B Series C May 2024 led by SoftBank with Microsoft and NVIDIA participation',['SoftBank','Microsoft','NVIDIA','Eclipse Ventures','Balderton Capital'],[ev('2024-05-07','official','Wayve official: $1.05B Series C led by SoftBank with NVIDIA and Microsoft to accelerate embodied AI for autonomous driving.','https://wayve.ai/thinking/series-c-funding/','high'),ev('2024-05-07','media','Reuters/major media covered UK Wayve $1.05B round; valuation not official in company release.','https://www.reuters.com/technology/uk-autonomous-driving-startup-wayve-raises-105-bln-softbank-led-funding-2024-05-07/','medium_high')],'Revenue likely pilot/strategic; commercial deployments and OEM contracts require data-room proof','Wayve — UK embodied AI/autonomous driving核心资产，技术叙事强、投资人强；估值需核，IPO更偏中长期。','主要风险：自动驾驶商业化周期、监管/安全、OEM adoption、训练/仿真成本、Tesla/Waymo/Mobileye竞争。','Verify valuation, OEM contracts, revenue/backlog, safety metrics, compute/data moat, path to production and capital needs.',priority='A2｜Embodied AI strategic watch / long IPO horizon',tags=['UK','autonomous driving','embodied AI'],ipo='medium_low',revenueq='low'),
comp('cmr-surgical','CMR Surgical','United Kingdom','Healthcare / Surgical robotics','Versius surgical robotic systems for minimally invasive surgery','Screenshot seed $2.7B; public 2021 Series D valued company around $3B, current mark requires verification','$600M Series D Jun 2021 led by SoftBank Vision Fund 2 and Ally Bridge; later financings need verification',['SoftBank Vision Fund 2','Ally Bridge Group','Tencent','LGT','Cambridge Innovation Capital'],[ev('2021-06','official','CMR Surgical official: $600M Series D to accelerate global commercialization of Versius surgical robot.','https://cmrsurgical.com/news/cmr-surgical-raises-600-million-series-d-financing/','high'),ev('2021','media','Media reported CMR Surgical valuation around $3B after Series D; screenshot $2.7B needs current verification.','https://www.reuters.com/','medium')],'Installed base/revenue not fully public; procedure volumes and regulatory approvals need current diligence','CMR Surgical — 英国手术机器人资产，赛道稀缺但资本强度高；截图$2.7B接近2021估值但需查当前down/up round。','主要风险：FDA/CE/regulatory, hospital adoption, procedure volume, service/support cost, Intuitive Surgical competition, cash burn.','Verify installed base, procedure volumes, regulatory approvals, revenue, gross margin/service cost, cash runway and latest valuation.',priority='B2｜Healthcare robotics / capital-intensive watch',layer='EMEA ECM / Healthcare robotics',tags=['UK','healthcare','surgical robotics'],risk='high',ipo='medium_low',revenueq='low'),
comp('huma','Huma','United Kingdom','Healthcare / Remote patient monitoring','Remote patient monitoring, digital health and decentralized clinical trials platform','Screenshot seed $1.3B; public unicorn valuation from 2021/2024 financing requires exact current verification','2021 $130M Series C; 2024 financing/strategic round reported around $80M+; valuation >$1B reported',['Leaps by Bayer','Hitachi Ventures','Samsung Next','AstraZeneca','Unilever Ventures'],[ev('2021','official','Huma official: $130M Series C to scale digital health/remote patient monitoring platform.','https://www.huma.com/news','medium_high'),ev('2024','media','Media reports: Huma raised additional financing and maintained unicorn status; screenshot $1.3B needs current source verification.','https://techcrunch.com/','medium')],'Revenue not public; regulatory clearances, patient volumes and pharma contracts require diligence','Huma — remote monitoring/digital clinical platform，医疗SaaS属性强但商业质量不透明；需要收入和监管证据。','主要风险：digital health reimbursement, clinical evidence, privacy/regulatory, hospital/pharma sales cycles, cash burn.','Verify revenue/ARR, pharma and hospital contracts, regulatory clearances, patient volume, gross margin and latest valuation.',priority='B2｜Healthcare software / revenue proof needed',layer='EMEA ECM / Healthcare digital platform',tags=['UK','healthcare','remote monitoring'],risk='medium_high'),
comp('medical-microinstruments','Medical Microinstruments','Italy','Healthcare / Surgical robotics','Symani robotic microsurgery platform','Valuation undisclosed in screenshot and public sources; keep undisclosed','$110M Series C Feb 2024 led by Fidelity Management & Research; valuation undisclosed',['Fidelity Management & Research','DPI','RA Capital','Andera Partners','Panakès Partners','Sambatech'],[ev('2024-02','official','MMI official: $110M Series C to accelerate commercialization of Symani surgical robotic system.','https://www.mmimicro.com/news/medical-microinstruments-raises-110-million-series-c-financing','high'),ev('2026','official','MMI official product site for Symani robotic microsurgery platform.','https://www.mmimicro.com/','high')],'Revenue not public; commercialization/installed base and regulatory status need diligence','Medical Microinstruments — 意大利微创/显微手术机器人，估值未披露；技术稀缺但商业化早期。','主要风险：regulatory approvals, procedure adoption, training, capital equipment sales cycle, cash burn, competition.','Verify Symani installed base, procedure volumes, FDA/CE status, revenue/backlog, gross margin, cash runway and next financing/IPO path.',priority='C1｜Healthcare robotics tech radar',layer='EMEA ECM / Healthcare robotics',tags=['Italy','healthcare','surgical robotics'],risk='high',ipo='low',revenueq='low'),
comp('owkin','Owkin','France','Healthcare / AI drug discovery','AI biotech using federated learning and multimodal data for drug discovery/precision medicine','Screenshot bottom cut off; public valuation: >$1B unicorn after Sanofi $180M investment in 2021','Nov 2021 $180M equity investment/strategic collaboration with Sanofi; later collaborations/funding need verification',['Sanofi','Bpifrance','GV','F-Prime Capital','Eight Roads','Bristol Myers Squibb'],[ev('2021-11','official','Owkin/Sanofi official: $180M equity investment and strategic collaboration; Owkin became unicorn at >$1B valuation.','https://www.owkin.com/news/owkin-and-sanofi-announce-strategic-collaboration','high'),ev('2026','official','Owkin official site positions company as AI biotech for drug discovery and precision medicine.','https://www.owkin.com/','high')],'Revenue not public; pharma milestones/partnership economics and clinical pipeline require diligence','Owkin — 法国AI drug discovery/precision medicine独角兽，截图估值不可见；以Sanofi/BMS等合作质量而非简单估值判断。','主要风险：AI biotech临床转化、milestone收入不确定、数据合作权利、药物研发周期、估值陈旧。','Verify current valuation, cash runway, pharma collaboration economics, pipeline milestones, data-network exclusivity and IPO/strategic exit route.',priority='B2｜AI biotech / partnership proof needed',layer='EMEA ECM / Healthcare AI biotech',tags=['France','healthcare','AI drug discovery'],risk='high',ipo='medium_low',revenueq='low'),
]

funding = [
fr('lendable','Lendable','2022-03-10','Primary + secondary financing','~£210M / $210M','>£3.5B',["Ontario Teachers’ Pension Plan"],["Ontario Teachers’ Pension Plan"],'Reuters','media','https://www.reuters.com/markets/deals/uk-fintech-lendable-valued-more-than-35-billion-funding-round-2022-03-10/','medium_high','Valuation broadly matches screenshot $4.7B depending FX.'),
fr('mirakl','Mirakl','2021-09-21','Series E','$555M','>$3.5B',['Silver Lake'],['Permira','83North','Felix Capital','Elaia','Bpifrance'],'Mirakl official','company press release','https://www.mirakl.com/news/mirakl-raises-555m-series-e-funding','high','Stale but public verified valuation.'),
fr('multiverse-computing','Multiverse Computing','2025','Series B','~€189M / ~$215M','~$500M',['Bullhound Capital'],['HP Tech Ventures','Forgepoint','CDP Venture Capital','Santander','Toshiba'],'media/company cluster','media','https://multiversecomputing.com/','medium','Round/valuation need definitive term-sheet confirmation.'),
fr('nord-security','Nord Security','2023-09-28','Financing','$100M','$3B',['Warburg Pincus'],['Novator','General Catalyst','Burda Principal Investments'],'Nord Security official','company press release','https://nordsecurity.com/blog/nord-security-raises-100m','high','Public verified valuation.'),
fr('oxford-quantum-circuits','Oxford Quantum Circuits','2023-11-27','Series B','$100M','undisclosed',['SBI Investment'],['Oxford Science Enterprises','University of Tokyo Edge Capital','Lansdowne','Prosus'],'OQC official','company press release','https://oqc.tech/news/oqc-raises-100m-series-b/','high','Valuation undisclosed.'),
fr('personio','Personio','2022-06-22','Series E extension','$200M','$8.5B',['Greenoaks'],['Altimeter','Index Ventures','Accel','Meritech','Lightspeed','Northzone'],'Personio official','company press release','https://www.personio.com/about-personio/press/personio-raises-200-million-series-e-extension/','high','Screenshot matches public verified valuation.'),
fr('poolside','Poolside','2024-10','Series B','$500M','$3B',['Bain Capital Ventures'],['DST Global','NVIDIA','eBay','Felicis','Redpoint'],'TechCrunch','media','https://techcrunch.com/2024/10/02/poolside-raises-500m-from-e-bay-nvidia-and-others-to-build-a-code-gen-ai/','medium_high','Public media valuation; commercial metrics not public.'),
fr('qonto','Qonto','2022-01-11','Series D','€486M','€4.4B / ~$5B',['Tiger Global','TCV'],['Tencent','DST','Alkeon','Valar','Eurazeo','Korelya'],'Qonto official','company press release','https://qonto.com/en/press/qonto-series-d','high','Screenshot matches public verified valuation but stale.'),
fr('quantexa','Quantexa','2025-03','Series F','$175M','$2.6B',['Teachers’ Venture Growth'],['Warburg Pincus','Dawn Capital','AlbionVC','HSBC','BNY','ABN AMRO'],'Quantexa official','company press release','https://www.quantexa.com/resources/quantexa-announces-175m-series-f-funding-round/','high','Fresh public valuation.'),
fr('thought-machine','Thought Machine','2022-05','Series D','$160M','~$2.7B public media / screenshot $2.1B current mark unverified',['Temasek'],['Intesa Sanpaolo','Morgan Stanley','JPMorgan Chase','Lloyds','Eurazeo'],'Thought Machine official','company press release','https://www.thoughtmachine.net/news/thought-machine-raises-160m-series-d','high','Need current secondary mark.'),
fr('trendyol','Trendyol','2021-08-09','Equity financing','$1.5B','$16.5B',['General Atlantic'],['SoftBank Vision Fund','ADQ','Qatar Investment Authority','Princeville','Alibaba'],'TechCrunch / Reuters','media','https://techcrunch.com/2021/08/09/turkeys-trendyol-raises-1-5b-at-a-16-5b-valuation/','medium_high','Stale 2021 valuation.'),
fr('wayve','Wayve','2024-05-07','Series C','$1.05B','not officially disclosed / screenshot seed $8.6B',['SoftBank'],['Microsoft','NVIDIA'],'Wayve official','company press release','https://wayve.ai/thinking/series-c-funding/','high','Company did not disclose valuation in official release.'),
fr('cmr-surgical','CMR Surgical','2021-06','Series D','$600M','~$3B media / screenshot $2.7B',['SoftBank Vision Fund 2','Ally Bridge'],['Tencent','LGT','Cambridge Innovation Capital'],'CMR Surgical official','company press release','https://cmrsurgical.com/news/cmr-surgical-raises-600-million-series-d-financing/','high','Valuation needs current verification.'),
fr('medical-microinstruments','Medical Microinstruments','2024-02','Series C','$110M','undisclosed',['Fidelity Management & Research'],['DPI','RA Capital','Andera Partners','Panakès'],'MMI official','company press release','https://www.mmimicro.com/news/medical-microinstruments-raises-110-million-series-c-financing','high','Valuation undisclosed.'),
fr('owkin','Owkin','2021-11','Strategic equity investment','$180M','>$1B',['Sanofi'],['Bpifrance','GV','F-Prime','Eight Roads'],'Owkin/Sanofi official','company press release','https://www.owkin.com/news/owkin-and-sanofi-announce-strategic-collaboration','high','Unicorn valuation; screenshot bottom did not show valuation.'),
]

# Patch existing records that were visible in screenshots.
patches = {
 'kraken-technology': {
   'latestValuation': 'Official: $8.65B Dec 2025 Kraken spin-out valuation; screenshot rounds this to $9.0B',
   'notes': 'Second screenshot confirms Kraken Technology row: SaaS for utilities / spinout of Octopus Energy / Last Valuation $9,000m. Public official source states $8.65B; keep official figure and note screenshot rounded banker-list value.',
   'keyMetrics': ['$8.65B official spin-out valuation / screenshot $9.0B rounded', '90M+ customer accounts', '15+ countries', '85% client NPS', 'up to 15GWh managed daily'],
 },
 'lovable': {
   'latestValuation': 'Screenshot seed $6.0B; existing public/media tracker has ~$6.6B Series B signal and earlier $1.8B Series A; verify current mark',
   'latestFunding': 'Existing tracker: $200M Series A led by Accel at $1.8B; later Series B media/secondary signals around $6B+ need primary verification',
   'revenueScale': 'Media claims: rapid ARR/run-rate growth; public source quality mixed. Need paid production ARR and retention proof.',
   'investmentSummaryZh': 'Lovable — 截图再次出现AI coding assistant/vibe coding，估值约$6B；已有tracker记录更高媒体mark。维持应用层观察，只有在ARR、留存和企业化证明后才上调。',
   'keyMetrics': ['screenshot seed $6.0B', 'media Series A $1.8B', 'media Series B ~$6B+', 'ARR/run-rate claims need verification'],
 },
 'mistral-ai': {
   'latestValuation': 'Screenshot seed $13.7B; public/media signals around €11.7B/$13B after 2025 ASML-led round; higher funding-talk marks require verification',
   'revenueScale': 'ARR/revenue not publicly audited; enterprise/API revenue and compute gross margin need data-room proof.',
   'investmentSummaryZh': 'Mistral AI — 欧洲主权LLM/enterprise AI核心资产，截图$13.7B与公开ASML-led round mark大致一致；战略价值高但IPO确定性和商业毛利仍需核验。',
   'priorityTier': 'A2｜European sovereign AI / strategic pre-IPO watch',
   'keyMetrics': ['screenshot seed $13.7B', 'ASML strategic investor', 'enterprise AI + LLM developer', 'ARR/GM not public'],
 },
 'synthesia': {
   'latestValuation': 'Screenshot seed $4.0B; existing public/media tracker: CNBC $4B valuation, ARR $150M and expected >$200M in 2026',
   'revenueScale': 'Media: ARR about $150M, expected >$200M in 2026; verify enterprise retention and gross margin.',
   'investmentSummaryZh': 'Synthesia — AI video creation应用层龙头，截图$4B与既有tracker一致；收入规模强但仍需验证企业留存、视频生成成本和平台替代风险。',
   'keyMetrics': ['$4B valuation', '$150M ARR media', 'expected >$200M ARR in 2026 media', 'AI video creation software'],
 },
}

extra_funding = [
fr('mistral-ai','Mistral AI','2025','Strategic growth round','~€1.7B media/official cluster','~€11.7B / screenshot $13.7B',['ASML'],['General Catalyst','Lightspeed','a16z','Bpifrance','NVIDIA'],'Mistral/ASML media cluster','media/official','https://mistral.ai/','medium','Use as public mark; verify final terms.'),
fr('synthesia','Synthesia','2026','Growth financing / media','~$200M media','~$4B',['Accel / existing investors'],['GV','Kleiner Perkins','NVIDIA'],'CNBC media cluster','media','https://www.cnbc.com/','medium','Existing tracker evidence; verify primary documents.'),
]

tasks = [task(c['id'], 'Verify current secondary/primary terms, revenue quality and IPO route for ' + c['name'], 'High' if c['id'] in {'quantexa','wayve','mistral-ai','kraken-technology','personio','qonto'} else 'Medium') for c in companies]
for cid in patches:
    tasks.append(task(cid, f'Patch/check screenshot valuation and latest data-room metrics for {cid}', 'High' if cid in {'mistral-ai','kraken-technology'} else 'Medium'))

state=json.loads(STATE.read_text())
idx={c['id']:i for i,c in enumerate(state['companies'])}
added=[]; patched=[]
for c in companies:
    if c['id'] in idx:
        state['companies'][idx[c['id']]].update(c); patched.append(c['id'])
    else:
        state['companies'].append(c); added.append(c['id'])
for cid, patch in patches.items():
    if cid in {c['id'] for c in state['companies']}:
        i={c['id']:i for i,c in enumerate(state['companies'])}[cid]
        state['companies'][i].update(patch)
        state['companies'][i]['updatedAt']=NOW
        state['companies'][i]['tags']=sorted(set(state['companies'][i].get('tags',[])+['EMEA ECM screenshot 2026-07-01']))
        patched.append(cid)

fr_idx={r.get('id'):i for i,r in enumerate(state.get('fundingRounds',[]))}
for r in funding+extra_funding:
    if r['id'] in fr_idx: state['fundingRounds'][fr_idx[r['id']]].update(r)
    else: state.setdefault('fundingRounds',[]).append(r)

t_idx={t.get('id'):i for i,t in enumerate(state.get('tasks',[]))}
for t in tasks:
    if t['id'] in t_idx: state['tasks'][t_idx[t['id']]].update(t)
    else: state.setdefault('tasks',[]).append(t)

meta=state.setdefault('meta',{})
meta['asOf']=ASOF; meta['updatedAt']=NOW
meta['coverage']=(meta.get('coverage','')+' Added second EMEA ECM screenshot batch covering Legora, Lendable, Mews, Mirakl, Multiverse Computing, n8n, Nord Security, Odoo, OQC, Personio, Poolside, Qonto, Quantexa, Thought Machine, Trendyol, Wayve, CMR Surgical, Huma, Medical Microinstruments, Owkin; patched Kraken, Lovable, Mistral AI, Synthesia.')[-1800:]
meta.setdefault('releaseNotes',[]).append({'version':'v8-emea-ecm-screenshot-batch2','date':ASOF,'items':['Added 20 new EMEA ECM screenshot companies across TMT and Healthcare.','Patched Kraken Technology, Lovable, Mistral AI and Synthesia screenshot valuation context.','Preserved low-confidence caveats where screenshot valuations were not open-source corroborated.']})
meta['dataEnrichment']={'asOf':ASOF,'method':'second user screenshot OCR + public official/media enrichment; no gated APIs; caveats preserved','companies':len(state['companies']),'addedFromEmeaEcmScreenshotBatch2':added,'patched':sorted(set(patched)),'fundingRowsAddedOrPatched':len(funding)+len(extra_funding)}
STATE.write_text(json.dumps(state,ensure_ascii=False,indent=2),encoding='utf-8')
print(json.dumps({'added':added,'patched':sorted(set(patched)),'companies':len(state['companies']),'fundingRounds':len(state.get('fundingRounds',[])),'tasks':len(state.get('tasks',[]))},ensure_ascii=False,indent=2))
